import type { XrpldInput, XrpldPortConfig } from '../types/xrpld-input.js';

// #region -- Header -----------------------------------

const CFG_HEADER = `# xrpld configuration file
# Generated by xrpld-config-generator
`;

// #endregion -- Header --------------------------------

// #region -- Primitive Renderers ----------------------

export function renderSingleValueSection(name: string, value: string | number | undefined): string {
  if (value === undefined) return '';
  return `[${name}]\n${value}\n`;
}

export function renderKeyValueSection(
  name: string,
  pairs: Record<string, unknown> | undefined
): string {
  if (!pairs) return '';
  const lines: string[] = [];
  for (const [key, val] of Object.entries(pairs)) {
    if (val === undefined) continue;
    lines.push(`${key}=${val}`);
  }
  if (lines.length === 0) return '';
  return `[${name}]\n${lines.join('\n')}\n`;
}

export function renderListSection(name: string, items: ReadonlyArray<unknown> | undefined): string {
  if (!items || items.length === 0) return '';
  const lines = items.map((item) => {
    if (typeof item === 'object' && item !== null) {
      return JSON.stringify(item);
    }
    return String(item);
  });
  return `[${name}]\n${lines.join('\n')}\n`;
}

// #endregion -- Primitive Renderers -------------------

// #region -- Port Renderers ---------------------------

export function renderPortSection(port: XrpldPortConfig): string {
  const lines: string[] = [];
  for (const [key, val] of Object.entries(port)) {
    if (key === 'name' || val === undefined) continue;
    lines.push(`${key} = ${val}`);
  }
  return `[${port.name}]\n${lines.join('\n')}\n`;
}

export function renderServerSection(
  ports: ReadonlyArray<XrpldPortConfig>,
  config?: Partial<XrpldInput>
): string {
  const lines = ports.map((p) => p.name);
  if (config?.ssl_key) lines.push(`ssl_key = ${config.ssl_key}`);
  if (config?.ssl_cert) lines.push(`ssl_cert = ${config.ssl_cert}`);
  if (config?.ssl_chain) lines.push(`ssl_chain = ${config.ssl_chain}`);
  if (config?.ssl_ciphers) lines.push(`ssl_ciphers = ${config.ssl_ciphers}`);
  return `[server]\n${lines.join('\n')}\n`;
}

// #endregion -- Port Renderers ------------------------

// #region -- Single-Value Section Keys ----------------

const SINGLE_VALUE_KEYS: ReadonlyArray<keyof XrpldInput> = [
  'debug_logfile',
  'database_path',
  'ssl_verify',
  'node_size',
  'ledger_history',
  'fetch_depth',
  'peer_private',
  'network_id',
  'network_quorum',
  'fee_default',
  'workers',
  'io_workers',
  'prefetch_workers',
  'sweep_interval',
  'path_search',
  'path_search_old',
  'path_search_fast',
  'path_search_max',
  'peers_max',
  'peers_in_max',
  'peers_out_max',
  'max_transactions',
  'compression',
  'signing_support',
  'beta_rpc_api',
  'ledger_replay',
  'websocket_ping_frequency',
  'server_domain',
  'elb_support',
  'amendment_majority_time',
  'rpc_allow_remote',
  'ssl_verify_file',
  'ssl_verify_dir',
  'validators_file',
  'validation_seed',
  'validator_token',
  'validator_key_revocation',
  'node_seed',
  'relay_proposals',
  'relay_validations',
];

// #endregion -- Single-Value Section Keys -------------

// #region -- List Section Keys ------------------------

const LIST_KEYS: ReadonlyArray<keyof XrpldInput> = [
  'sntp_servers',
  'ips',
  'ips_fixed',
  'cluster_nodes',
  'amendments',
  'veto_amendments',
  'rpc_startup',
];

// #endregion -- List Section Keys ---------------------

// #region -- Key-Value Section Keys -------------------

const KEY_VALUE_KEYS: ReadonlyArray<keyof XrpldInput> = [
  'node_db',
  'overlay',
  'transaction_queue',
  'voting',
  'crawl',
  'reduce_relay',
  'insight',
  'perf',
  'sqlite',
  'import_db',
];

// #endregion -- Key-Value Section Keys ----------------

// #region -- Main Renderer ----------------------------

export function renderXrpldCfg(config: XrpldInput): string {
  const sections: string[] = [CFG_HEADER];

  // Server + ports (ssl_key/ssl_cert/ssl_chain/ssl_ciphers rendered inside [server])
  if (config.server?.ports && config.server.ports.length > 0) {
    if (config.server_comment) {
      sections.push(
        `${config.server_comment}\n${renderServerSection(config.server.ports, config)}`
      );
    } else {
      sections.push(renderServerSection(config.server.ports, config));
    }
    for (const port of config.server.ports) {
      sections.push(renderPortSection(port));
    }
  }

  // Node DB (key-value but rendered first among key-value sections)
  if (config.node_db) {
    sections.push(
      renderKeyValueSection('node_db', config.node_db as unknown as Record<string, unknown>)
    );
  }

  // Single-value sections
  for (const key of SINGLE_VALUE_KEYS) {
    const value = config[key];
    if (value !== undefined && typeof value !== 'object') {
      sections.push(renderSingleValueSection(key, value as string | number));
    }
  }

  // List sections
  for (const key of LIST_KEYS) {
    const value = config[key];
    if (Array.isArray(value)) {
      sections.push(renderListSection(key, value as ReadonlyArray<unknown>));
    }
  }

  // Key-value sections (skip node_db, already rendered)
  for (const key of KEY_VALUE_KEYS) {
    if (key === 'node_db') continue;
    const value = config[key];
    if (value && typeof value === 'object' && !Array.isArray(value)) {
      sections.push(renderKeyValueSection(key, value as unknown as Record<string, unknown>));
    }
  }

  // Filter empty sections and join with blank line separator
  return sections.filter((s) => s.length > 0).join('\n');
}

// #endregion -- Main Renderer -------------------------
