packages:
  - packages/**

catalog:
  '@types/node': 25.3.0
  autoprefixer: ^10.4.24
  esbuild: ^0.27.3
  fs-extra: ^11.3.3
  lodash: ^4.17.23
  path: ^0.12.7
  prettier: ^3.8.1
  tailwindcss: ^4.2.1
  ts-jest: ^29.4.6
  tsc-alias: ^1.8.16
  typescript: ^6.0.2
  vitest: ^3.2.4

cleanupUnusedCatalogs: true
