#!/bin/bash
# Scylla ENV defaults (CQL auth, keyspace, binary).
# ENV: SCYLLA_CLUSTER_NAME, SCYLLA_SEEDS, SCYLLA_LISTEN_ADDRESS, SCYLLA_RPC_ADDRESS,
#      SCYLLA_AUTHENTICATOR, SCYLLA_AUTHORIZER, SCYLLA_NATIVE_TRANSPORT_PORT,
#      SCYLLA_USERNAME, SCYLLA_PASSWORD, SCYLLA_CQLSH_USER, SCYLLA_CQLSH_PASSWORD,
#      SCYLLA_CLIO_KEYSPACE (default clio; set empty to skip), SCYLLA_BIN

SCYLLA_OPTIONS_FILE=""
SCYLLA_PID=""

export SCYLLA_CQLSH_USER="${SCYLLA_CQLSH_USER:-cassandra}"
export SCYLLA_CQLSH_PASSWORD="${SCYLLA_CQLSH_PASSWORD:-cassandra}"
export SCYLLA_USERNAME="${SCYLLA_USERNAME:-cassandra}"
