services:
  xrpld:
    build:
      context: .
      dockerfile: ./images/envt.dockerfile
    container_name: xrpld
    restart: unless-stopped
    labels:
      - "com.docker.compose.project=simulate"
      - "com.docker.compose.service=xrpld"
      - "description=XRP Ledger Node Image"
    healthcheck:
      test: [ "CMD", "rippled", "server_info" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - "51234:51234"
      - "6005:6005"
    networks:
      simulation-net:
        ipv4_address: 172.30.0.3
