services:
  scylla:
    build:
      context: ../../packages/docker/scylla
      dockerfile: ./images/base.dockerfile
    container_name: scylla
    restart: unless-stopped
    env_file:
      - ../credentials.env
    labels:
      - "com.docker.compose.project=simulate"
      - "com.docker.compose.service=scylla"
      - "description=ScyllaDB Sample Service"
    ports:
      - "9042:9042"
    healthcheck:
      test: [ "CMD-SHELL", "cqlsh -u \"${SCYLLA_SUPER_USERNAME:-cassandra}\" -p \"${SCYLLA_SUPER_PASSWORD:-cassandra}\" -e 'describe cluster' || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      docker-simulate-net:
        ipv4_address: 10.201.0.10
